// Generated by CodiumAI
import { getChartData } from '.';
import { Request, Response } from 'express';
import {
  createRequest,
  createResponse,
  MockRequest,
  MockResponse,
} from 'node-mocks-http';
import data from 'stubData/chartData.json';

describe('getChartData function', () => {
  let mockResponse: MockResponse<Response>;
  let mockRequest = {} as MockRequest<Request>;

  beforeEach(() => {
    mockRequest = createRequest();
    mockResponse = createResponse();
  });

  // Tests that response status is 200
  it('test response status 200', async () => {
    await getChartData(mockRequest, mockResponse);
    expect(mockResponse.statusCode).toEqual(200);
  });

  // Tests that response data is sent
  it('test response data sent', async () => {
    await getChartData(mockRequest, mockResponse);
    expect(mockResponse._getData()).toEqual(data);
  });
});
